### ISSUE TITLE
Reorder 'Back' Buttons on data download

### ISSUE THREAD

**Issue by christoball** [TNRIS/tnris.org#627] opened 2015-10-07 17:13 UTC
I think the ordering of the back buttons on the data download should be reordered. They should work like breadcrumbs, where the furthest back is on the left, i.e. Texas. This also coincides with the arrow pointing to the left.

@wilsaj do you think this is a good idea?

![image](https://cloud.githubusercontent.com/assets/1877550/10345071/95781632-6cec-11e5-8d52-02d552592c8e.png)

**Comment by wilsaj** [comment] 2015-10-13 00:32
I agree that the ordering is slightly counter intuitive, but I don't think switching the order is the answer. The issue is that when changing between County and Quad views, the buttons will end up moving too much. Example:

1. You are at the County level: then only Texas button is shown.
2. You go from County -> Quad: then Texas button moves to the left, and the County button appears where Texas button used to be.

This is visually distracting and it means that the far-right button changes meaning depending on which level you are at (sometimes takes you to Texas, sometimes to County). 

Another issue is if navigating between quads in counties ("Bee County" -> "San Patricio County") the county button size may change considerably, shifting the Texas button farther to the left. Also distracting.

I think the counter-intuitive ordering is the lesser of the two evils here.

**Comment by wilsaj** [comment] 2015-11-18 18:23
ok to close this @christoball ?

**Comment by christoball** [comment] 2015-11-18 18:27
One last suggestion - what if we keep the order as is and just changed the arrows to point the other way?

**Comment by wilsaj** [comment] 2015-11-18 18:54
I'm not opposed to changing the icon up, but I don't think that just flipping the icon is a good idea. The icon is already a reversed version of the "share" icon: http://fortawesome.github.io/Font-Awesome/icon/share/
So that would directly make it a version of the share icon. Which isn't really what we're dealing with here.

The action that will take place is "zooming out", so maybe we should find an icon that indicates that?

Might be neat to have one icon per county of the county outline and a Texas icon for the Texas button. That would be a bit of work, though.

**Comment by christoball** [comment] 2015-11-18 18:57
We already have the texas icon, its up in the nav.

As for county outline, I like that idea, just gotta make 256 icons :sweat_smile:

**Comment by wilsaj** [comment] 2015-11-18 19:10
We can automate most of it, and it is probably worth researching on icon sets to figure out the best way to build and serve them (for example, as a webfont). Could be neat stand-alone project that would be probably be useful to other people.

**Comment by jseppi** [comment] 2015-11-18 19:15
webfonts are over, svgs are in

**Comment by jseppi** [comment] 2015-11-18 19:17
We could relatively easily go from county GeoJSON (https://github.com/tnris/tx.geojson) to simplified SVG (using ogr2ogr probably).

**Comment by wilsaj** [comment] 2015-11-18 19:34
Here's a similar thing: http://propublica.github.io/stateface/

**Closed** 2017-05-23 00:12 UTC
Labels: question
